### ISSUE TITLE
StackOverflowError for regexp with unescaped "@" symbol.

### ISSUE THREAD

**Issue by RayzRazko** [mifmif/Generex#21]
Got `java.lang.StackOverflowError` if I try to generate random string with regexp that contains unescaped "@" symbol:
```
Generex rnd = new Generex("[a-z]@mail.com"); 
System.out.println(rnd.random());
//specifying the boundaries doesn't help 
Generex rnd = new Generex("[a-z]@mail.com"); 
System.out.println(rnd.random(20, 50));

```
while next line is totally ok for Java Pattern:
`Pattern.compile("[a-z]@mail.com").matcher("m@mail.com").matches()`

Generex works fine with next patterns:` "[a-z]\\@mail.com"`, `"[a-z][@]mail.com"`.

Stack:
```
java.lang.StackOverflowError
	at java.util.TimSort.countRunAndMakeAscending(TimSort.java:355)
	at java.util.TimSort.sort(TimSort.java:220)
	at java.util.Arrays.sort(Arrays.java:1438)
	at dk.brics.automaton.State.getSortedTransitionArray(Unknown Source)
	at dk.brics.automaton.State.getSortedTransitions(Unknown Source)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:282)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:303)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:303)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:303)
	at com.mifmif.common.regex.Generex.prepareRandom(Generex.java:303)
.....

```

**Comment by mifmif** [comment]
it seams that the @ is interpreted as a meta char , i will fix this issue.

**Comment by mifmif** [comment]
you can now use the feature  discussed in issue #22 to avoid interpreting Metacharacter like @
